DEBUG = False

DATABASE_FILENAME = "spider-web.db"

API_AUTHENTICATION_METHOD = "BASIC_AUTHENTICATION" # Choices are BEARER_TOKEN or BASIC_AUTHENTICATION.
API_CREDENTIAL_FORMAT = "USERNAME_PASSWORD" # Choices are REFRESH_TOKEN or USERNAME_PASSWORD.
API_KEY_FILE_PATH = "spider-web.key"
API_CONNECTION_TIMEOUT = 30

LOG_ENABLE_LOGGING = True
LOG_FILENAME = "spider-web.log"
LOG_MAX_BYTES_PER_FILE = 1000000
LOG_MAX_NUMBER_LOG_FILES = 3
LOG_LEVEL = 20  #Level: CRITICAL=50, ERROR=40, WARNING=30, INFO=20, DEBUG=10, NOTSET=0
LOG_FORMAT = "%(asctime)s — %(levelname)s — %(message)s"

USE_PROXY = False
PROXY_URL = "https://PROXYURLHERE"
PROXY_PORT = 8080
PROXY_USERNAME = "PROXY USERNAME HERE"
PROXY_PASSWORD = "PROXY PASSWORD HERE"
VERIFY_HTTPS_CERTIFICATE = True